# vim: set ft=ansible
# site.yml
---

- hosts: rhel_mirrors
  become: true
  tags:
    - rhel_register
  vars_files:
    - "./vars/main.yml"
    - ~/.ansible/vars/rhel_local_mirrors_vars.yml
  vars:
    sudo_defaults:
      - defaults: '!requiretty'
  tasks:
    - include: rhel_register.yml
      when: subscribe_rhn|bool == True
      tags:
        - rhel_register
    - include: prepare_system.yml
      tags:
        - prepare_system
    - include: create_mirror.yml
      tags:
        - create_mirror
    - include: prepare_cron.yml
      when: repo_autosync|bool == True
      tags:
        - prepare_cron

    - include: remove_cron.yml
      when: repo_autosync|bool == False
      tags:
        - prepare_cron
